library(plyr)
library(Formula)
library(gmnl)
library(mlogit)
set.seed(1118)

##load dried_environment
load("C:/Users/m_xue/Desktop/RA/Cranberry-gene/code&results/v2/gmnl/dried_1.RData")

##obtain the unconditional WTP
wtpc_or_tr1[[2]]$coefficients["Regular"]
wtpc_or_tr1[[2]]$coefficients["Gene"]
wtpc_or_tr1[[2]]$coefficients["BlandFlavor"]
cor.gmnl(wtpc_or_tr1[[2]])
vcov(wtpc_or_tr1[[2]],what="ranp",trpe="cov",se="true")

##calculate tradeoff sd
##delta method
##Regular sugar
u_Regular = wtpc_or_tr1[[2]]$coefficients["Regular"]
u_Gene = wtpc_or_tr1[[2]]$coefficients["Gene"]
sd_Regular = wtpc_or_tr1[[2]]$coefficients["sd.Regular.Regular"]
sd_Gene = wtpc_or_tr1[[2]]$coefficients["sd.Gene.Gene"]
sd_RegularGene = wtpc_or_tr1[[2]]$coefficients["sd.Regular.Gene"]## square root of covariance 
sdratio_Regular_Gene = sqrt(u_Regular**2*sd_Gene**2/u_Gene**4 - 2*u_Regular*sd_RegularGene**2/u_Gene**3+sd_Regular**2/u_Gene**2)
##bland flavor
u_BlandFlavor = wtpc_or_tr1[[2]]$coefficients["BlandFlavor"]
u_Gene = wtpc_or_tr1[[2]]$coefficients["Gene"]
sd_BlandFlavor = wtpc_or_tr1[[2]]$coefficients["sd.BlandFlavor.BlandFlavor"]
sd_Gene = wtpc_or_tr1[[2]]$coefficients["sd.Gene.Gene"]
sd_BlandFlavorGene = wtpc_or_tr1[[2]]$coefficients["sd.Gene.BlandFlavor"]
sdratio_BlandFlavor_Gene = sqrt(u_BlandFlavor**2*sd_Gene**2/u_Gene**4 - 2*u_BlandFlavor*sd_BlandFlavorGene**2/u_Gene**3+sd_BlandFlavor**2/u_Gene**2)

### Unconditional trade off ###################################
set.seed(1118)
##Regular sugar
un_tradeoff_Regular_tr1 <- u_Regular/u_Gene + sdratio_Regular_Gene*rnorm(250)
mean(un_tradeoff_Regular_tr1)
##BlandFlavor
set.seed(1118)
un_tradeoff_BlandFlavor_tr1 <- u_BlandFlavor/u_Gene + sdratio_BlandFlavor_Gene*rnorm(250)
mean(un_tradeoff_BlandFlavor_tr1)

##generate PersonID 
idd=c()
for (i in 1:250){
  idd[i]=mydata_tr1$PersonID[i*18]
}
idd
##generate file of individual wtp
df1=data.frame(PersonID=idd,to_Regular=un_tradeoff_Regular_tr1,to.BlandFlavor=un_tradeoff_BlandFlavor_tr1)
##generate individual wtp csv file
write.csv(df1,"C:/Users/m_xue/Desktop/RA/Cranberry-gene/code&results/v2/latent class/tradeoff_dried_1.csv", 
          row.names = TRUE)

##import the socio-demographi file that generated by stata
setwd("C:/Users/m_xue/Desktop/RA/Cranberry-gene/data clean/new latent")
socio1<-read.csv('Dried_Total_1.csv', fileEncoding = 'UTF-8-BOM')

##merge the individual wtp csv file with stata file of socio-demographic
df11=merge(df1, socio1, by = "PersonID")

##save to the dried_1_mixedlogit
write.csv(df11,"C:/Users/m_xue/Desktop/RA/Cranberry-gene/code&results/v2/latent class/ols_tradeoff_dried_1.csv", 
          row.names = TRUE)


################################################################################
#################################  OLS REGRESSION  #############################
################################################################################

library(MASS)
library(leaps)

setwd("C:/Users/m_xue/Desktop/RA/Cranberry-gene/code&results/v2/latent class")
mydata<-read.csv('ols_tradeoff_dried_1.csv', fileEncoding = 'UTF-8-BOM')
head(mydata)

#### Regular 
##knowdiffis should not be included
##old should not be included
ols_Regular <- lm(to_Regular ~ female+millennial+hedu+hinc+lfamily+child_dummy+agri+local+environmental+health+farmer_owned
                  +privatebrand+therapeutic_diet+nfl+ingredient+servingsize+calories+totalsugarcontent+sugaradded+lowcaloriesweeteners+carbohydrates+nutrition_infomation
                  +relativeprice+interpret+main_total+intenseflavor+presentation+taste+flavor+nutrient_import+nutrition_overall+taste_overall+healthy+chronic+neophobic
                  +consumer_ori+producer_ori+scientific+sff+gov+know_conventional1+know_ge1+know_gm1+knowle_ge+knowmod_ge+dontknow+only_dummy+fac_cul_dummy
                  +red_env_dummy+inc_nutr_dummy+red_sug_dummy+fruit_dummy+product_dummy+pay_fruit_dummy+pay_products_dummy
                  , data = mydata)
summary(ols_Regular)

step=stepAIC(ols_Regular,direction="both")

ols_Regular_1 <- lm(to_Regular ~ hinc + lfamily + agri + environmental + sugaradded + 
                      intenseflavor + taste_overall + producer_ori + know_conventional1 + 
                      fac_cul_dummy + inc_nutr_dummy, data=mydata)
summary(ols_Regular_1)

ols_Regular_2 <- lm(to_Regular ~ hinc + lfamily + agri + environmental + sugaradded + 
                      intenseflavor + taste_overall + producer_ori + know_conventional1 + 
                      fac_cul_dummy + inc_nutr_dummy + product_dummy, data=mydata)
summary(ols_Regular_2)

ols_Regular_3 <- lm(to_Regular ~ hinc + lfamily + agri + environmental + sugaradded + 
                      intenseflavor + taste_overall + producer_ori + scientific + 
                      know_conventional1 + fac_cul_dummy + inc_nutr_dummy + product_dummy, data=mydata)
summary(ols_Regular_3)

ols_Regular_4 <- lm(to_Regular ~ hinc + lfamily + agri + environmental + sugaradded + 
                      intenseflavor + taste_overall + producer_ori + scientific + 
                      know_conventional1 + know_ge1 + fac_cul_dummy + inc_nutr_dummy + 
                      product_dummy, data=mydata)
summary(ols_Regular_4)

ols_Regular_5 <- lm(to_Regular ~  millennial + hinc + lfamily + agri + environmental + sugaradded + 
                      intenseflavor + taste_overall + producer_ori + scientific + 
                      know_conventional1 + know_ge1 + fac_cul_dummy + inc_nutr_dummy + 
                      product_dummy, data=mydata)
summary(ols_Regular_5)


### BlandFlavoror
ols_bf <- lm(to.BlandFlavor ~ female+millennial+hedu+hinc+lfamily+child_dummy+agri+local+environmental+health+farmer_owned
             +privatebrand+therapeutic_diet+nfl+ingredient+servingsize+calories+totalsugarcontent+sugaradded+lowcaloriesweeteners+carbohydrates+nutrition_infomation
             +relativeprice+interpret+main_total+intenseflavor+presentation+taste+flavor+nutrient_import+nutrition_overall+taste_overall+healthy+chronic+neophobic
             +consumer_ori+producer_ori+scientific+sff+gov+know_conventional1+know_ge1+know_gm1+knowle_ge+knowmod_ge+dontknow+only_dummy+fac_cul_dummy
             +red_env_dummy+inc_nutr_dummy+red_sug_dummy+fruit_dummy+product_dummy+pay_fruit_dummy+pay_products_dummy, data = mydata)
summary(ols_bf)

step=stepAIC(ols_bf,direction="both")

ols_bf_1 <- lm(to.BlandFlavor ~ hinc + lfamily + agri + environmental + sugaradded + 
                 intenseflavor + taste_overall + producer_ori + know_conventional1 + 
                 fac_cul_dummy + inc_nutr_dummy, data=mydata)
summary(ols_bf_1)

ols_bf_2 <- lm(to.BlandFlavor ~ hinc + lfamily + agri + environmental + sugaradded + 
                 intenseflavor + taste_overall + producer_ori + know_conventional1 + 
                 fac_cul_dummy + inc_nutr_dummy + product_dummy, data=mydata)
summary(ols_bf_2)

ols_bf_3 <- lm(to.BlandFlavor ~ hinc + lfamily + agri + environmental + sugaradded + 
                 intenseflavor + taste_overall + producer_ori + scientific + 
                 know_conventional1 + fac_cul_dummy + inc_nutr_dummy + product_dummy, data=mydata)
summary(ols_bf_3)

ols_bf_4 <- lm(to.BlandFlavor ~ hinc + lfamily + agri + environmental + sugaradded + 
                 intenseflavor + taste_overall + producer_ori + scientific + 
                 know_conventional1 + know_ge1 + fac_cul_dummy + inc_nutr_dummy + 
                 product_dummy
               , data=mydata)
summary(ols_bf_4)

ols_bf_5 <- lm(to.BlandFlavor ~ millennial + hinc + lfamily + agri + environmental + 
                 sugaradded + intenseflavor + taste_overall + producer_ori + 
                 scientific + know_conventional1 + know_ge1 + fac_cul_dummy + 
                 inc_nutr_dummy + product_dummy, data=mydata)
summary(ols_bf_5)


################################################################################
#################################  LATENT CLASS  ###############################
################################################################################

#---------------------------------------------------------------------------
#-----------------------------  TREATMENT 1  -------------------------------
#---------------------------------------------------------------------------
#install.packages("https://cran.r-project.org/src/contrib/Archive/mlogit/mlogit_1.0-2.tar.gz",repos=NULL,type="source")

library(plyr)
library(Formula)
library(gmnl)
library(mlogit)
set.seed(1118)

setwd("C:/Users/m_xue/Desktop/RA/Cranberry-GENE/data clean/new latent")
mydata<-read.csv('Dried_Total_1_latent.csv', fileEncoding = 'UTF-8-BOM')
head(mydata)
tail(mydata)

##generate group variable, named id
mydata$id=c()
for (i in 1:4500){
  mydata$id[i]=ceiling(i/3)
}
##change name of alternatives
for (i in 1:4500){
  if (mydata$altern[i]==1){mydata$altern[i]="Option1"}
  else if (mydata$altern[i]==2){mydata$altern[i]="Option2"}
  else if (mydata$altern[i]==3){mydata$altern[i]="Option3"}}
head(mydata)

##generate Regular sugar content variable
##labeled the alternative with Regular sugar content as 1
mydata$Regular=c()
for (i in 1:4500){
  if (mydata$tsugar[i]==12){mydata$Regular[i]=1}
  else if (mydata$tsugar[i]!=12){mydata$Regular[i]=0}
}
head(mydata)

##labeled the alternative with reduced sugar content as 1
mydata$Reduced=c()
for (i in 1:4500){
  if (mydata$tsugar[i]==14){mydata$Reduced[i]=1}
  else if (mydata$tsugar[i]!=14){mydata$Reduced[i]=0}
}

mydata$Regular=c()
for (i in 1:4500){
  if (mydata$tsugar[i]==29){mydata$Regular[i]=1}
  else if (mydata$tsugar[i]!=29){mydata$Regular[i]=0}
}
head(mydata)

##generate bland flavor variable
mydata$BlandFlavor=1-mydata$fullflav
for (i in 1:1500){
  mydata$BlandFlavor[3*i]=0
}
head(mydata)

mean(mydata$fullflav)
mean(mydata$BlandFlavor)


##reshape dataset into gmnl format by using mlogit.data
TM <- mlogit.data(mydata,choice="choice",shape="long",alt.var="altern",
                  chid.var="id",id.var="personid")
head(TM)

#---------------------- 3 classes -----------------------#
##add socio-economic charateristics in the fifth part
latent_3 <- gmnl(choice~price+Regular+gene+BlandFlavor+opt|0|0|0|
                   hinc+sugaradded+interpret+main_total+intenseflavor+health+ingredient
                 +knowle_ge+knowmod_ge+dontknow
                 +only_dummy+fac_cul_dummy+red_env_dummy+inc_nutr_dummy+red_sug_dummy, 
                 data=TM,
                 panel=TRUE,
                 model="lc",
                 iterlim=500,
                 Q=3, ##3 classes
                 method="bhhh",
)
## bhhh, not working
## default method, two slightly wierd estimates
## nr not better than default
summary(latent_3)
AIC(latent_3)
BIC(latent_3)
getSummary.gmnl(latent_3)

##Conditional probabilities of classes each individual belongs to
pi_hat <- latent_3$Qir
colnames(pi_hat) <- c("q = 1", "q = 2", "q = 3")
dim(pi_hat)
round(pi_hat, 4)

##share
exp(coef(latent_3)["(class)2"]) / (exp(0) + exp(coef(latent_3)["(class)2"]) 
                                   + exp(coef(latent_3)["(class)3"]))
exp(coef(latent_3)["(class)3"]) / (exp(0) + exp(coef(latent_3)["(class)2"]) 
                                   + exp(coef(latent_3)["(class)3"]))

##wtp for each class
-coef(latent_3)["class.1.Regular"] / coef(latent_3)["class.1.price"]
-coef(latent_3)["class.1.gene"] / coef(latent_3)["class.1.price"]
-coef(latent_3)["class.1.BlandFlavor"] / coef(latent_3)["class.1.price"]
-coef(latent_3)["class.2.Regular"] / coef(latent_3)["class.2.price"]
-coef(latent_3)["class.2.gene"] / coef(latent_3)["class.2.price"]
-coef(latent_3)["class.2.BlandFlavor"] / coef(latent_3)["class.2.price"]
-coef(latent_3)["class.3.Regular"] / coef(latent_3)["class.3.price"]
-coef(latent_3)["class.3.gene"] / coef(latent_3)["class.3.price"]
-coef(latent_3)["class.3.BlandFlavor"] / coef(latent_3)["class.3.price"]


##trade off for each class
-coef(latent_3)["class.1.Regular"] / coef(latent_3)["class.1.gene"]
-coef(latent_3)["class.1.BlandFlavor"] / coef(latent_3)["class.1.gene"]
-coef(latent_3)["class.2.Regular"] / coef(latent_3)["class.2.gene"]
-coef(latent_3)["class.2.BlandFlavor"] / coef(latent_3)["class.2.gene"]
-coef(latent_3)["class.3.Regular"] / coef(latent_3)["class.3.gene"]
-coef(latent_3)["class.3.BlandFlavor"] / coef(latent_3)["class.3.gene"]

#---------------------- 2 classes -----------------------#
latent_2 <- gmnl(choice~price+Regular+gene+BlandFlavor+opt|0|0|0|
                   hinc+sugaradded+interpret+main_total+intenseflavor+health+ingredient
                 +knowle_ge+knowmod_ge+dontknow
                 +only_dummy+fac_cul_dummy+red_env_dummy+inc_nutr_dummy+red_sug_dummy,  
                 data=TM,
                 panel=TRUE,
                 model="lc",
                 method="nr",
                 #iterlim=500,
                 Q=2)
summary(latent_2)
AIC(latent_2)
BIC(latent_2)

##share
exp(coef(latent_2)["(class)2"]) / (exp(0) + exp(coef(latent_2)["(class)2"]))

##wtp for each class
-coef(latent_2)["class.1.Regular"] / coef(latent_2)["class.1.price"]
-coef(latent_2)["class.1.gene"] / coef(latent_2)["class.1.price"]
-coef(latent_2)["class.1.BlandFlavor"] / coef(latent_2)["class.1.price"]
-coef(latent_2)["class.2.Regular"] / coef(latent_2)["class.2.price"]
-coef(latent_2)["class.2.gene"] / coef(latent_2)["class.2.price"]
-coef(latent_2)["class.2.BlandFlavor"] / coef(latent_2)["class.2.price"]

##trade off for each class
-coef(latent_2)["class.1.Regular"] / coef(latent_2)["class.1.gene"]
-coef(latent_2)["class.1.BlandFlavor"] / coef(latent_2)["class.1.gene"]
-coef(latent_2)["class.2.Regular"] / coef(latent_2)["class.2.gene"]
-coef(latent_2)["class.2.BlandFlavor"] / coef(latent_2)["class.2.gene"]


#---------------------- 4 classes -----------------------#
latent_4 <- gmnl(choice~price+Regular+gene+BlandFlavor+opt|0|0|0|
                   hinc+sugaradded+interpret+main_total+intenseflavor+health+ingredient
                 +knowle_ge+knowmod_ge+dontknow
                 +only_dummy+fac_cul_dummy+red_env_dummy+inc_nutr_dummy+red_sug_dummy, 
                 data=TM,
                 R=500,
                 panel=TRUE,
                 model="lc",
                 Q=4, 
                 #reltol=1e-50,
                 #method="nr",
                 #print.level=2,
                 iterlim=500)
summary(latent_4)
AIC(latent_4)
BIC(latent_4)

##share
exp(coef(latent_4)["(class)2"]) / (exp(0) + exp(coef(latent_4)["(class)2"]) 
                                   + exp(coef(latent_4)["(class)3"])
                                   +exp(coef(latent_4)["(class)4"]))
exp(coef(latent_4)["(class)3"]) / (exp(0) + exp(coef(latent_4)["(class)2"]) 
                                   + exp(coef(latent_4)["(class)3"])
                                   +exp(coef(latent_4)["(class)4"]))
exp(coef(latent_4)["(class)4"]) / (exp(0) + exp(coef(latent_4)["(class)2"]) 
                                   + exp(coef(latent_4)["(class)3"])
                                   +exp(coef(latent_4)["(class)4"]))

##wtp for each class
-coef(latent_4)["class.1.Regular"] / coef(latent_4)["class.1.price"]
-coef(latent_4)["class.1.gene"] / coef(latent_4)["class.1.price"]
-coef(latent_4)["class.1.BlandFlavor"] / coef(latent_4)["class.1.price"]
-coef(latent_4)["class.2.Regular"] / coef(latent_4)["class.2.price"]
-coef(latent_4)["class.2.gene"] / coef(latent_4)["class.2.price"]
-coef(latent_4)["class.2.BlandFlavor"] / coef(latent_4)["class.2.price"]
-coef(latent_4)["class.3.Regular"] / coef(latent_4)["class.3.price"]
-coef(latent_4)["class.3.gene"] / coef(latent_4)["class.3.price"]
-coef(latent_4)["class.3.BlandFlavor"] / coef(latent_4)["class.3.price"]
-coef(latent_4)["class.4.Regular"] / coef(latent_4)["class.4.price"]
-coef(latent_4)["class.4.gene"] / coef(latent_4)["class.4.price"]
-coef(latent_4)["class.4.BlandFlavor"] / coef(latent_4)["class.4.price"]

##trade off for each class
-coef(latent_4)["class.1.Regular"] / coef(latent_4)["class.1.gene"]
-coef(latent_4)["class.1.BlandFlavor"] / coef(latent_4)["class.1.gene"]
-coef(latent_4)["class.2.Regular"] / coef(latent_4)["class.2.gene"]
-coef(latent_4)["class.2.BlandFlavor"] / coef(latent_4)["class.2.gene"]
-coef(latent_4)["class.3.Regular"] / coef(latent_4)["class.3.gene"]
-coef(latent_4)["class.3.BlandFlavor"] / coef(latent_4)["class.3.gene"]
-coef(latent_4)["class.4.Regular"] / coef(latent_4)["class.4.gene"]
-coef(latent_4)["class.4.BlandFlavor"] / coef(latent_4)["class.4.gene"]


source('lc_helpers.R')
plot_ci_lc(latent_4)  # Plot coefficients and 95% CI
plot_ci_lc(lc, var = c())  # Plot significant coefficients

